version: '3.1'

services:
  
  jenkins:
    build: .
    restart: always
    ports:
      - 8082:8080
      - 50000:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./jenkins_ssh:/home/jenkins
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS="-Dhudson.model.DirectoryBrowserSupport.CSP="
      - JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF-8"

volumes:
  jenkins_home:
  jenkins_ssh:
