version: '3.1'

services:
  
  jenkins:
    build: .
    restart: always
    ports:
      - 8082:8080
      - 50000:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./jenkins_ssh:/home/jenkins
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home:
  jenkins_ssh:
